from worktree_env.envrc import write_envrc


class TestWriteEnvrc:
    def test_writes_file(self, tmp_path):
        path = write_envrc(
            tmp_path,
            {"DB_NAME": "myapp_dev_main"},
            {"PORT": 4000},
        )
        assert path.exists()
        content = path.read_text()
        assert "export DB_NAME=myapp_dev_main" in content
        assert "export PORT=4000" in content

    def test_header_comment(self, tmp_path):
        write_envrc(tmp_path, {}, {})
        content = (tmp_path / ".envrc").read_text()
        assert "Generated by worktree-env" in content

    def test_quotes_values_with_spaces(self, tmp_path):
        write_envrc(tmp_path, {"X": "hello world"}, {})
        content = (tmp_path / ".envrc").read_text()
        assert 'export X="hello world"' in content

    def test_sorted_output(self, tmp_path):
        write_envrc(
            tmp_path,
            {"Z_VAR": "z", "A_VAR": "a"},
            {"M_PORT": 5000},
        )
        content = (tmp_path / ".envrc").read_text()
        lines = [l for l in content.splitlines() if l.startswith("export")]
        keys = [l.split("=")[0].replace("export ", "") for l in lines]
        assert keys == sorted(keys)
