import shutil
import subprocess
from pathlib import Path


def write_envrc(
    path: Path,
    env_vars: dict[str, str],
    ports: dict[str, int],
) -> Path:
    envrc_path = path / ".envrc"

    lines = ["# Generated by worktree-env — do not edit manually", ""]

    merged = {}
    for name, value in ports.items():
        merged[name] = str(value)
    merged.update(env_vars)

    for key, value in sorted(merged.items()):
        lines.append(f"export {key}={_shell_quote(value)}")

    lines.append("")
    envrc_path.write_text("\n".join(lines))
    return envrc_path


def _shell_quote(value: str) -> str:
    if _is_safe(value):
        return value
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _is_safe(value: str) -> bool:
    import re
    return bool(re.match(r"^[a-zA-Z0-9_./:-]+$", value))


def run_direnv_allow(path: Path) -> bool:
    if not shutil.which("direnv"):
        return False
    try:
        subprocess.run(
            ["direnv", "allow"],
            cwd=path,
            capture_output=True,
            check=True,
        )
        return True
    except subprocess.CalledProcessError:
        return False
